In [1]:
#comparison of all models to evaluate best performance on a single independent variable dataset, ridge with the next a larger data set

In [ ]:
#multivariable linear regression

In [ ]:
#multivariable polynomial regression

In [ ]:
#normal regression gradient descent  (stochastic, batch, mini batch)

In [ ]:
#ols

In [ ]:
#scikit learn

In [ ]:
#lasso ridge

In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
os.chdir("C:\\Users\\Madhura\\Desktop\\projects\\From scratch\\Linear Regression with gradient descent\\")

In [4]:
df= pd.read_csv("Salary_dataset.csv")

In [5]:
df.shape

(30, 3)

In [6]:
df.head()

Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Unnamed: 0       30 non-null     int64  
 1   YearsExperience  30 non-null     float64
 2   Salary           30 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 852.0 bytes


In [8]:
y=df.iloc[:,-1]

In [10]:
y

0      39344.0
1      46206.0
2      37732.0
3      43526.0
4      39892.0
5      56643.0
6      60151.0
7      54446.0
8      64446.0
9      57190.0
10     63219.0
11     55795.0
12     56958.0
13     57082.0
14     61112.0
15     67939.0
16     66030.0
17     83089.0
18     81364.0
19     93941.0
20     91739.0
21     98274.0
22    101303.0
23    113813.0
24    109432.0
25    105583.0
26    116970.0
27    112636.0
28    122392.0
29    121873.0
Name: Salary, dtype: float64

In [9]:
X=df.iloc[:,:-1]

In [12]:
X

Unnamed: 0  YearsExperience
0            0              1.2
1            1              1.4
2            2              1.6
3            3              2.1
4            4              2.3
5            5              3.0
6            6              3.1
7            7              3.3
8            8              3.3
9            9              3.8
10          10              4.0
11          11              4.1
12          12              4.1
13          13              4.2
14          14              4.6
15          15              5.0
16          16              5.2
17          17              5.4
18          18              6.0
19          19              6.1
20          20              6.9
21          21              7.2
22          22              8.0
23          23              8.3
24          24              8.8
25          25              9.1
26          26              9.6
27          27              9.7
28          28             10.4
29          29             10.6

In [10]:
X=X.drop(columns=["Unnamed: 0"])

In [14]:
X


YearsExperience
0               1.2
1               1.4
2               1.6
3               2.1
4               2.3
5               3.0
6               3.1
7               3.3
8               3.3
9               3.8
10              4.0
11              4.1
12              4.1
13              4.2
14              4.6
15              5.0
16              5.2
17              5.4
18              6.0
19              6.1
20              6.9
21              7.2
22              8.0
23              8.3
24              8.8
25              9.1
26              9.6
27              9.7
28             10.4
29             10.6

# Using regression formula and gradient descent
[Single variable dependency]

In [11]:
X_mean=X.mean()
X_mean

YearsExperience    5.413333
dtype: float64

In [12]:
y_mean=y.mean()
y_mean

76004.0

Model

In [20]:
a = 0.0
sum_of_squares = 0.0
for i in range (30):
    a = a + (X.iloc[i]-X_mean)*(y[i]-y_mean)

for i in range(30):
    sum_of_squares = sum_of_squares + (X.iloc[i]-X_mean)**2
a = a/sum_of_squares
a

YearsExperience    9449.962321
dtype: float64

In [21]:
b = y_mean - a*X_mean
b

YearsExperience    24848.203967
dtype: float64

R - squared value

In [26]:
def calc(X,y,y_mean,a,b):
    error_squared = 0.0
    y_mean_diff_squared = 0.0
    for i in range (30):
        error_squared = error_squared + (y[i]-(a*X[i]+b))**2
    for i in range (30):
        y_mean_diff_squared = y_mean_diff_squared + (y[i]-y_mean)**2
        
    return error_squared/y_mean_diff_squared #here y and X are already numpy arrays, cell run after converting them to arrays

In [27]:
r_square = 1 - calc(X,y,y_mean,a,b)
r_square

YearsExperience    0.956957
dtype: float64

In [20]:
#95% of the variance in target can be explained by the model

In [32]:
y_pred = (float)(a)*X + (float)(b)
y_pred

array([ 36188.15875227,  38078.15121656,  39968.14368085,  44693.12484158,
        46583.11730587,  53198.09093089,  54143.08716303,  56033.07962732,
        56033.07962732,  60758.06078805,  62648.05325234,  63593.04948449,
        63593.04948449,  64538.04571663,  68318.03064522,  72098.0155738 ,
        73988.00803809,  75878.00050238,  81547.97789525,  82492.9741274 ,
        90052.94398456,  92887.932681  , 100447.90253816, 103282.8912346 ,
       108007.87239533, 110842.86109176, 115567.84225249, 116512.83848464,
       123127.81210966, 125017.80457395])

Gradient Descent

In [22]:
X.to_numpy()

array([[ 1.2],
       [ 1.4],
       [ 1.6],
       [ 2.1],
       [ 2.3],
       [ 3. ],
       [ 3.1],
       [ 3.3],
       [ 3.3],
       [ 3.8],
       [ 4. ],
       [ 4.1],
       [ 4.1],
       [ 4.2],
       [ 4.6],
       [ 5. ],
       [ 5.2],
       [ 5.4],
       [ 6. ],
       [ 6.1],
       [ 6.9],
       [ 7.2],
       [ 8. ],
       [ 8.3],
       [ 8.8],
       [ 9.1],
       [ 9.6],
       [ 9.7],
       [10.4],
       [10.6]])

In [42]:
y.to_numpy()

array([ 39344.,  46206.,  37732.,  43526.,  39892.,  56643.,  60151.,
        54446.,  64446.,  57190.,  63219.,  55795.,  56958.,  57082.,
        61112.,  67939.,  66030.,  83089.,  81364.,  93941.,  91739.,
        98274., 101303., 113813., 109432., 105583., 116970., 112636.,
       122392., 121873.])

In [43]:
y_pred.to_numpy()

array([[ 36188.15875227],
       [ 38078.15121656],
       [ 39968.14368085],
       [ 44693.12484158],
       [ 46583.11730587],
       [ 53198.09093089],
       [ 54143.08716303],
       [ 56033.07962732],
       [ 56033.07962732],
       [ 60758.06078805],
       [ 62648.05325234],
       [ 63593.04948449],
       [ 63593.04948449],
       [ 64538.04571663],
       [ 68318.03064522],
       [ 72098.0155738 ],
       [ 73988.00803809],
       [ 75878.00050238],
       [ 81547.97789525],
       [ 82492.9741274 ],
       [ 90052.94398456],
       [ 92887.932681  ],
       [100447.90253816],
       [103282.8912346 ],
       [108007.87239533],
       [110842.86109176],
       [115567.84225249],
       [116512.83848464],
       [123127.81210966],
       [125017.80457395]])

In [15]:
y.shape

(30,)

In [16]:
X.shape

(30, 1)

In [33]:
y_pred.shape

(30,)

In [34]:
np.inner((y_pred-y),(y_pred-y))/(30)
#mean squared error

31270951.722280953

In [35]:
np.linalg.norm(y_pred-y)/np.sqrt(len(y))
#root mean squared error

5592.04360876066

In [52]:
y_pred = y_pred.to_numpy().reshape(30,)


In [24]:
y = y.to_numpy()

In [25]:
X = X.to_numpy().reshape(30,)

In [36]:
X.shape

(30,)

In [178]:
y.shape

(30,)

In [69]:
y_pred.shape

(30,)

In [118]:
X_norm = (X-X.mean())/X.std() # to avoid shooting around of grandient

In [194]:
def partial_derivatives(X,y,y_pred):
    dJda= -np.inner(X,(y_pred-y))/len(y)
    dJdb= -np.sum(y_pred-y)/len(y)
    return dJda,dJdb

In [201]:
def mod_weights(X,y,a,b,alpha):
    X= np.asarray(X).reshape(-1)
    y = np.asarray(y).reshape(-1)
    a = float(a)
    b = float(b)
    y_pred = a*X + b
    for i in range (4000):
        
        dJda, dJdb = partial_derivatives(X,y,y_pred)
        a = a + alpha*dJda
        b = b + alpha*dJdb
        y_pred = a*X+ b
        print("Mean Squared error for epoch ",i, "is ", np.inner((y_pred-y),(y_pred-y))/(30))
        
    return a,b

In [202]:
a

YearsExperience    9449.962321
dtype: float64

In [203]:
b

YearsExperience    24848.203967
dtype: float64

In [211]:

final_a, final_b = mod_weights(X,y,100,2000,0.01)

Mean Squared error for epoch  0 is  2432770612.021036
Mean Squared error for epoch  1 is  1014239225.0707278
Mean Squared error for epoch  2 is  466679045.03466797
Mean Squared error for epoch  3 is  255176935.5079809
Mean Squared error for epoch  4 is  173341031.65954897
Mean Squared error for epoch  5 is  141536715.7495206
Mean Squared error for epoch  6 is  129037617.64221475
Mean Squared error for epoch  7 is  123988214.7458569
Mean Squared error for epoch  8 is  121814146.74587116
Mean Squared error for epoch  9 is  120750430.28680862
Mean Squared error for epoch  10 is  120116057.16279003
Mean Squared error for epoch  11 is  119648262.13385843
Mean Squared error for epoch  12 is  119245655.60501306
Mean Squared error for epoch  13 is  118869113.47016294
Mean Squared error for epoch  14 is  118503536.26854776
Mean Squared error for epoch  15 is  118143094.26778708
Mean Squared error for epoch  16 is  117785534.39972883
Mean Squared error for epoch  17 is  117429983.63812228
Mean S

In [212]:
final_a

9450.78596373556

In [213]:
final_b

24842.59206677101

In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np


In [50]:
class SciKit_Regression:
    def model_creation(X,y):
        model = LinearRegression()
        model.fit(X.reshape(-1,1), y)
        a = model.coef_[0]
        b = model.intercept_   # bias
        print(a, b)

        return model.predict(X.reshape(-1,1))
    def norm_model(X,y):
        from sklearn.preprocessing import StandardScaler

        scaler = StandardScaler()
        X_norm = scaler.fit_transform(X.reshape(-1,1))

        model = LinearRegression()
        model.fit(X_norm.reshape(-1,1), y)
        a = model.coef_[0]
        b = model.intercept_
        print(a, b)
        return model.predict(X_norm.reshape(-1,1))
        

    
    y_pred_scikit = model_creation(X,y)
    mse = mean_squared_error(y, y_pred)
    rmse = np.sqrt(mse)
    print("MSE: without scaling ",mse,"\nRMSE: without scaling ",rmse)
    y_pred_norm = norm_model(X,y)
    rmse_norm = np.sqrt(mean_squared_error(y, y_pred_norm))
    print("MSE: with scaling ",mse,"\nRMSE: with scaling ",rmse)
        
    
    

9449.962321455074 24848.203966523208
MSE: without scaling  31270951.722280953 
RMSE: without scaling  5592.04360876066
26367.18244354243 76003.99999999999
MSE: with scaling  31270951.722280953 
RMSE: with scaling  5592.04360876066


In [1]:
#learning about using libraries, pandas and numpy, data types, matrices and rmse and gradient descent and tuning of hyper-parameters 
#additionally comparing with ols, scikit learn, correlation coefficient math and GD
#next step can be polynomial regression
#remaining multivariable linear regression

# OLS implementation

In [24]:
class OLS:
    def calc_coefficient(X,y):
        numerator = 0.0
        denominator = 0.0
        for i in range (30):
            numerator = numerator + (X.iloc[i]-X_mean)*(y[i]-y_mean)
            denominator = denominator + (X.iloc[i]-X_mean)**2
            
        intercept = y_mean - numerator*X_mean/denominator
        slope = numerator/denominator
        return slope,intercept
    slope , intercept = calc_coefficient(X,y)
    print ("Slope is: ",slope, " Intercept is: ", intercept)


Slope is:  YearsExperience    9449.962321
dtype: float64  Intercept is:  YearsExperience    24848.203967
dtype: float64


#------------------------------------------------------The end!----------------------------------------------------------------

In [39]:

indices = np.arange(len(X))
np.random.shuffle(indices)


train_size = int(0.8 * len(X))
train_idx = indices[:train_size]
test_idx = indices[train_size:]

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]


In [70]:
type(y_train)

pandas.core.series.Series

In [46]:
X_train.shape


(24, 1)

In [47]:
y_train.shape


(24,)

In [54]:
first_fit= LinearRegression()

In [55]:
X_train*first_fit.w1

YearsExperience
13         126000.0
17         162000.0
20         207000.0
0           36000.0
14         138000.0
28         312000.0
4           69000.0
11         123000.0
18         180000.0
2           48000.0
26         288000.0
23         249000.0
15         150000.0
27         291000.0
25         273000.0
16         156000.0
19         183000.0
10         120000.0
8           99000.0
3           63000.0
12         123000.0
9          114000.0
6           93000.0
22         240000.0

In [56]:
X_train

YearsExperience
13              4.2
17              5.4
20              6.9
0               1.2
14              4.6
28             10.4
4               2.3
11              4.1
18              6.0
2               1.6
26              9.6
23              8.3
15              5.0
27              9.7
25              9.1
16              5.2
19              6.1
10              4.0
8               3.3
3               2.1
12              4.1
9               3.8
6               3.1
22              8.0

In [72]:
y_pred_train = (X_train*first_fit.w1).to_numpy()

In [73]:
y_pred_train

array([[126000.],
       [162000.],
       [207000.],
       [ 36000.],
       [138000.],
       [312000.],
       [ 69000.],
       [123000.],
       [180000.],
       [ 48000.],
       [288000.],
       [249000.],
       [150000.],
       [291000.],
       [273000.],
       [156000.],
       [183000.],
       [120000.],
       [ 99000.],
       [ 63000.],
       [123000.],
       [114000.],
       [ 93000.],
       [240000.]])

In [74]:
y_train=y_train.to_numpy()

In [77]:
 y_train

array([ 57082.,  83089.,  91739.,  39344.,  61112., 122392.,  39892.,
        55795.,  81364.,  37732., 116970., 113813.,  67939., 112636.,
       105583.,  66030.,  93941.,  63219.,  64446.,  43526.,  56958.,
        57190.,  60151., 101303.])

In [87]:
  y_train=y_train.reshape(-1,1)

In [88]:
y_pred_train.shape

(24, 1)

In [89]:
 y_train.shape

(24, 1)

In [94]:
Loss=(y_train-y_pred_train).T@(y_train-y_pred_train)
Loss

array([[2.44165358e+11]])

In [95]:
y_train-y_pred_train

array([[ -68918.],
       [ -78911.],
       [-115261.],
       [   3344.],
       [ -76888.],
       [-189608.],
       [ -29108.],
       [ -67205.],
       [ -98636.],
       [ -10268.],
       [-171030.],
       [-135187.],
       [ -82061.],
       [-178364.],
       [-167417.],
       [ -89970.],
       [ -89059.],
       [ -56781.],
       [ -34554.],
       [ -19474.],
       [ -66042.],
       [ -56810.],
       [ -32849.],
       [-138697.]])

In [104]:
print(X_train.T.shape)
print(X_train.shape)
np.linalg.inv(X_train.T@X_train)

(1, 24)
(24, 1)


array([[0.00117759]])

In [105]:
first_fit.w1=np.linalg.inv(X_train.T@X_train)@X_train.T@y_train
first_fit.w1

0
0  13157.732663

In [126]:
first_fit.w1= first_fit.toNumpy

pandas.core.frame.DataFrame

# Scikit Learn

In [132]:
from sklearn.linear_model import LinearRegression

# Assume X and y are NumPy arrays or Pandas DataFrame/Series
model_scikit = LinearRegression()
model_scikit.fit(X_train, y_train)        # Training
predictions = model_scikit.predict(X_test)  # Prediction

# Coefficients and intercept
print(model_scikit.coef_)     # slope(s)
print(model_scikit.intercept_)  # bias


[[9682.10312394]]
[23040.35790932]


In [107]:
predictions

array([[125670.65102305],
       [ 52086.66728113],
       [ 36595.30228283],
       [ 92751.50040167],
       [ 54991.29821831],
       [108242.86539997]])

In [127]:
X_test= X.iloc[test_idx]
type(X_test)
#X_test = X_test.to_numpy()

pandas.core.frame.DataFrame

In [129]:
X_test.to_numpy()*first_fit.w1.to_numpy()

array([[139471.96622664],
       [ 39473.19798867],
       [ 18420.82572805],
       [ 94735.67517281],
       [ 43420.51778754],
       [115788.04743344]])

# OLS method

In [133]:
import statsmodels.api as sm
X = sm.add_constant(X)
model_ols = sm.OLS(y, X).fit()
model_ols.params.tolist()

[24848.203966523168, 9449.962321455076]